Repository metal3-io/ironic-agent-image, pull requests merged in 2021-11, with the labels that each got.

#1 Run efibootmgr if boot mode is UEFI
  hardware_manager/ironic_coreos_install.py
Labels: size/S, lgtm, approved

#5 Remove redundancy in OWNERS
  OWNERS
Labels: size/XS, lgtm, approved

#7 Pre-generate default config during container build
  Dockerfile
  ironic-python-agent.conf
  runironicagent
Labels: lgtm, approved

#8 Copy configuration defaults from ironic-image
  ironic-python-agent.conf
Labels: size/XS, lgtm, approved
